### ISSUE TITLE
Uncaught Error: Cannot find module 'read-torrent'"

### ISSUE THREAD

**Issue by kumavis** [piratechest/piratechest#10]
```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/piratechest ‹node-v0.12.7›  (master) 
╰─$ npm run app

> PirateChest@0.0.3 app /Users/kumavis/dev/piratechest
> nw ./app

[1655:1004/231743:INFO:CONSOLE(0)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.", source:  (0)
[1655:1004/231743:INFO:CONSOLE(13)] ""rendered app://piratechest/less/app.less successfully."", source: app://piratechest/vendor/less.min.js (13)
[1655:1004/231743:INFO:CONSOLE(13)] ""css for app://piratechest/less/app.less generated in 119ms"", source: app://piratechest/vendor/less.min.js (13)
[1655:1004/231743:INFO:CONSOLE(13)] ""less has finished. css generated in 120ms"", source: app://piratechest/vendor/less.min.js (13)
[1655:1004/231744:INFO:CONSOLE(34)] ""Loading local config."", source: /Users/kumavis/dev/piratechest/app/src/models/Config.coffee (34)
[1655:1004/231744:ERROR:nw_shell.cc(336)] Error: Cannot find module 'read-torrent'
  at Function.Module._resolveFilename (module.js:327:15)
  at Function.Module._load (module.js:264:25)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/kumavis/dev/piratechest/app/src/views/BodyView.coffee:1:15)
  at Object.<anonymous> (/Users/kumavis/dev/piratechest/app/src/views/BodyView.coffee:1:1)
  at Module._compile (module.js:451:26)
  at Object.loadFile (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/kumavis/dev/piratechest/app/src/views/AppView.coffee:11:16)
  at Object.<anonymous> (/Users/kumavis/dev/piratechest/app/src/views/AppView.coffee:2:1)
  at Module._compile (module.js:451:26)
  at Object.loadFile (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/kumavis/dev/piratechest/app/src/app.coffee:19:15)
  at Object.<anonymous> (/Users/kumavis/dev/piratechest/app/src/app.coffee:1:1)
  at Module._compile (module.js:451:26)
  at Object.loadFile (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at window.require (<anonymous>:4:17)
  at app://piratechest/app.js:2:1

[1655:1004/231744:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'read-torrent'", source: module.js (329)
```

**Comment by kumavis** [comment]
this is ater `npm install`ing in both `/` and `/app`

**Comment by step21** [comment]
You can go around this by installing it manually. I might send a pull request with this added to package.json explicitly. Same for parse-torrent and file.

**Comment by step21** [comment]
Should be fixed in https://github.com/piratechest/piratechest/commit/b2fa9abaccbf4f83a61454d647604dc2a8ad4670
