### ISSUE TITLE
 "Uncaught Error: Module version mismatch. Expected 43, got 14."

### ISSUE THREAD

**Issue by kumavis** [piratechest/piratechest#11]
after filling in some missing dependencies, i got a little further:

```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/piratechest ‹node-v0.12.7›  (master*) 
╰─$ npm run app


> PirateChest@0.0.3 app /Users/kumavis/dev/piratechest
> nw ./app

[3852:1004/235545:INFO:CONSOLE(0)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.", source:  (0)
[3852:1004/235545:INFO:CONSOLE(13)] ""rendered app://piratechest/less/app.less successfully."", source: app://piratechest/vendor/less.min.js (13)
[3852:1004/235545:INFO:CONSOLE(13)] ""css for app://piratechest/less/app.less generated in 133ms"", source: app://piratechest/vendor/less.min.js (13)
[3852:1004/235545:INFO:CONSOLE(13)] ""less has finished. css generated in 134ms"", source: app://piratechest/vendor/less.min.js (13)
[3852:1004/235545:ERROR:nw_shell.cc(336)] Error: Module version mismatch. Expected 43, got 14.
  at Error (native)
  at Module.load (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/kumavis/dev/blockapps-web3/node_modules/ethereumjs-util/index.js:1:76)
  at Module._compile (module.js:451:26)
  at Object.Module._extensions..js (module.js:469:10)
  at Module.load (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/kumavis/dev/blockapps-web3/node_modules/ethereumjs-tx/index.js:1:79)
  at Module._compile (module.js:451:26)
  at Object.Module._extensions..js (module.js:469:10)
  at Module.load (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/kumavis/dev/blockapps-web3/build/blockapps-web3.js:943:11)
  at Module._compile (module.js:451:26)
  at Object.Module._extensions..js (module.js:469:10)
  at Module.load (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/kumavis/dev/piratechest/app/src/app.coffee:5:8)
  at Object.<anonymous> (/Users/kumavis/dev/piratechest/app/src/app.coffee:1:1)
  at Module._compile (module.js:451:26)
  at Object.loadFile (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at window.require (<anonymous>:4:17)
  at app://piratechest/app.js:2:1

[3852:1004/235545:INFO:CONSOLE(45)] "Uncaught Error: Module version mismatch. Expected 43, got 14.", source: /Users/kumavis/dev/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js (45)
[3852:1004/235545:ERROR:nw_shell.cc(336)] ReferenceError: Backbone is not defined
    at app://piratechest/vendor/backbone.search.js:154:3
[3852:1004/235545:INFO:CONSOLE(154)] "Uncaught ReferenceError: Backbone is not defined", source: app://piratechest/vendor/backbone.search.js (154)
```

**Comment by kumavis** [comment]
this is also b/c I repalced web3 with `blockapps-web3` for an experiment -- so maybe not your fault

**Comment by step21** [comment]
Hej, maybe try again with the latest code from git. Otherwise I would propose to close this unless you also have this problem with normal web3.
