### ISSUE TITLE
Fails To Start Properly on OS X 64

### ISSUE THREAD

**Issue by MosheBenZacharia** [piratechest/piratechest#13]
[45132:1113/125351:INFO:CONSOLE(0)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.", source:  (0)
[45132:1113/125351:INFO:CONSOLE(13)] ""rendered app://piratechest/less/app.less successfully."", source: app://piratechest/vendor/less.min.js (13)
[45132:1113/125351:INFO:CONSOLE(13)] ""css for app://piratechest/less/app.less generated in 107ms"", source: app://piratechest/vendor/less.min.js (13)
[45132:1113/125351:INFO:CONSOLE(13)] ""less has finished. css generated in 107ms"", source: app://piratechest/vendor/less.min.js (13)
[45132:1113/125351:ERROR:nw_shell.cc(335)] ~/Downloads/piratechest.app/Contents/Resources/app.nw/src/app.coffee:1
function (exports, require, module, __filename, __dirname) { fs = require 'fs'
                                                                          ^^^^
SyntaxError: Unexpected string
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:434:25)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at window.require (<anonymous>:4:17)
    at app://piratechest/app.js:2:1
[45132:1113/125351:INFO:CONSOLE(1)] "Uncaught SyntaxError: ~/Downloads/piratechest.app/Contents/Resources/app.nw/src/app.coffee:1
function (exports, require, module, __filename, __dirname) { fs = require 'fs'
                                                                          ^^^^
Unexpected string", source: 
~/Downloads/piratechest.app/Contents/Resources/app.nw/src/app.coffee (1)

**Comment by step21** [comment]
Please try again with source from Github, if you can. Might have been fixed in https://github.com/piratechest/piratechest/commit/b2fa9abaccbf4f83a61454d647604dc2a8ad4670
