### ISSUE TITLE
failure to connect to eth node / fail gracefully

### ISSUE THREAD

**Issue by step21** [piratechest/piratechest#14]
```[7392:1205/170941:INFO:CONSOLE(63)] ""Lodestone Ethererum RPC Node endpoint: " "http://localhost:8545"", source: /home/user/piratechest/app/src/models/Lodestone.coffee (63)
[7392:1205/170942:ERROR:nw_shell.cc(336)] Error: Invalid JSON RPC response
  at Object.module.exports.InvalidResponse (/home/user/piratechest/app/node_modules/web3/lib/web3/errors.js:35:16)
  at [object Object].HttpProvider.send (/home/user/piratechest/app/node_modules/web3/lib/web3/httpprovider.js:57:22)
  at [object Object].RequestManager.send (/home/user/piratechest/app/node_modules/web3/lib/web3/requestmanager.js:73:32)
  at [object Object].Method.send (/home/user/piratechest/app/node_modules/web3/lib/web3/method.js:168:59)
  at new Filter (/home/user/piratechest/app/node_modules/web3/lib/web3/filter.js:86:41)
  at Object.web3.shh.filter (/home/user/piratechest/app/node_modules/web3/lib/web3.js:104:12)
  at Lodestone.module.exports.Lodestone.Lodestone._listenForSearches (/home/user/piratechest/app/src/models/Lodestone.coffee:43:28)
  at new Lodestone (/home/user/piratechest/app/src/models/Lodestone.coffee:40:10)
  at Object.<anonymous> (/home/user/piratechest/app/src/app.coffee:66:25)
  at Object.<anonymous> (/home/user/piratechest/app/src/app.coffee:1:1)
  at Module._compile (module.js:451:26)
  at Object.loadFile (/home/user/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/user/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at window.require (<anonymous>:4:17)
  at app://piratechest/app.js:2:1
[7392:1205/170942:INFO:CONSOLE(57)] "Uncaught Error: Invalid JSON RPC response", source: /home/user/piratechest/app/node_modules/web3/lib/web3/httpprovider.js (57)

```
Assuming it is complaining that it cannot find a proper ethereum node connection, this should give a proper error message / fail more gracefully.
```

**Comment by step21** [comment]
(This is on Ubuntu 14.04.3 64bit)

**Comment by step21** [comment]
More or less fixed in https://github.com/piratechest/piratechest/commit/b2fa9abaccbf4f83a61454d647604dc2a8ad4670 but probably onle temporarily.
