### ISSUE TITLE
Uncaught Error: Cannot find module 'parse-torrent'", source: module.js

### ISSUE THREAD

**Issue by tseymour** [piratechest/piratechest#9]
I've installed it and get the nwjs icon at startup - nothing else.  I am starting with npm run app.

Tylers-MacBook-Air:piratechest tylerseymour$ npm run app

> PirateChest@0.0.3 app /Users/tylerseymour/piratechest
> nw ./app

[97431:0908/050716:INFO:CONSOLE(0)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.", source:  (0)
[97431:0908/050716:INFO:CONSOLE(13)] ""rendered app://piratechest/less/app.less successfully."", source: app://piratechest/vendor/less.min.js (13)
[97431:0908/050716:INFO:CONSOLE(13)] ""css for app://piratechest/less/app.less generated in 115ms"", source: app://piratechest/vendor/less.min.js (13)
[97431:0908/050716:INFO:CONSOLE(13)] ""less has finished. css generated in 115ms"", source: app://piratechest/vendor/less.min.js (13)
[97431:0908/050716:INFO:CONSOLE(34)] ""Loading local config."", source: /Users/tylerseymour/piratechest/app/src/models/Config.coffee (34)
[97431:0908/050716:ERROR:nw_shell.cc(336)] Error: Cannot find module 'parse-torrent'
  at Function.Module._resolveFilename (module.js:327:15)
  at Function.Module._load (module.js:264:25)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/tylerseymour/piratechest/app/src/models/Magnet.coffee:5:16)
  at Object.<anonymous> (/Users/tylerseymour/piratechest/app/src/models/Magnet.coffee:1:1)
  at Module._compile (module.js:451:26)
  at Object.loadFile (/Users/tylerseymour/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/tylerseymour/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at Object.<anonymous> (/Users/tylerseymour/piratechest/app/src/app.coffee:15:14)
  at Object.<anonymous> (/Users/tylerseymour/piratechest/app/src/app.coffee:1:1)
  at Module._compile (module.js:451:26)
  at Object.loadFile (/Users/tylerseymour/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/tylerseymour/piratechest/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:356:17)
  at require (module.js:375:17)
  at window.require (<anonymous>:4:17)
  at app://piratechest/app.js:2:1

[97431:0908/050716:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'parse-torrent'", source: module.js (329)

**Comment by d11e9** [comment]
@tseymour Did you do: `npm install` first?

**Comment by step21** [comment]
Yeah, this happens even after doing `npm install` in both places. Manually installing it fixes it.

**Comment by step21** [comment]
Should be fixed in https://github.com/piratechest/piratechest/commit/b2fa9abaccbf4f83a61454d647604dc2a8ad4670
